name: Pull Blogs

on:
  push:
    branches:
      - main

jobs:
  login:
    runs-on: ubuntu-latest

    steps:
      - name: Login Tencent
        uses: matheusvanzan/sshpass-action@v1
        with:
          host: $${{ secrets.TENCENT_IP }}
          username: $${{ secrets.TENCENT_USER }}
          password: ${{ secrets.TENCENT_PWD }}

      - name: Pull Blogs
        run: cd static-blogs && echo "Pull Start..." && git pull origin main
