name: Pull Blogs

on:
  push:
    branches:
      - main

jobs:
  login:
    name: login tencent and pull blogs
    runs-on: ubuntu-latest

    steps:
      - name: Login Tencent
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.TENCENT_IP }}
          username: ${{ secrets.TENCENT_USER }}
          password: ${{ secrets.TENCENT_PWD }}
          command: cd ~/static-blogs && git pull origin main
